python webis_dbscan_script.py true BOW 0.05 2
python webis_dbscan_script.py true BOW 0.05 3
python webis_dbscan_script.py true BOW 0.05 5
python webis_dbscan_script.py true BOW 0.05 8
python webis_dbscan_script.py true BOW 0.05 10
python webis_dbscan_script.py true BOW 0.05 15
python webis_dbscan_script.py true BOW 0.1 2
python webis_dbscan_script.py true BOW 0.1 3
python webis_dbscan_script.py true BOW 0.1 5
python webis_dbscan_script.py true BOW 0.1 8
python webis_dbscan_script.py true BOW 0.1 10
python webis_dbscan_script.py true BOW 0.1 15
python webis_dbscan_script.py false BOW 0.2 2
python webis_dbscan_script.py false BOW 0.2 3
python webis_dbscan_script.py false BOW 0.2 5
python webis_dbscan_script.py false BOW 0.2 8
python webis_dbscan_script.py false BOW 0.2 10
python webis_dbscan_script.py false BOW 0.2 15
python webis_dbscan_script.py false BOW 0.3 2
python webis_dbscan_script.py false BOW 0.3 3
python webis_dbscan_script.py false BOW 0.3 5
python webis_dbscan_script.py false BOW 0.3 8
python webis_dbscan_script.py false BOW 0.3 10
python webis_dbscan_script.py false BOW 0.3 15
python webis_dbscan_script.py true TFIDF 0.05 2
python webis_dbscan_script.py true TFIDF 0.05 3
python webis_dbscan_script.py true TFIDF 0.05 5
python webis_dbscan_script.py true TFIDF 0.05 8
python webis_dbscan_script.py true TFIDF 0.05 10
python webis_dbscan_script.py true TFIDF 0.05 15
python webis_dbscan_script.py true TFIDF 0.1 2
python webis_dbscan_script.py true TFIDF 0.1 3
python webis_dbscan_script.py true TFIDF 0.1 5
python webis_dbscan_script.py true TFIDF 0.1 8
python webis_dbscan_script.py true TFIDF 0.1 10
python webis_dbscan_script.py true TFIDF 0.1 15
python webis_dbscan_script.py false TFIDF 0.2 2
python webis_dbscan_script.py false TFIDF 0.2 3
python webis_dbscan_script.py false TFIDF 0.2 5
python webis_dbscan_script.py false TFIDF 0.2 8
python webis_dbscan_script.py false TFIDF 0.2 10
python webis_dbscan_script.py false TFIDF 0.2 15
python webis_dbscan_script.py false TFIDF 0.3 2
python webis_dbscan_script.py false TFIDF 0.3 3
python webis_dbscan_script.py false TFIDF 0.3 5
python webis_dbscan_script.py false TFIDF 0.3 8
python webis_dbscan_script.py false TFIDF 0.3 10
python webis_dbscan_script.py false TFIDF 0.3 15
