python webis_dbscan_script.py true LDA_10 0.05 2
python webis_dbscan_script.py true LDA_10 0.05 3
python webis_dbscan_script.py true LDA_10 0.05 5
python webis_dbscan_script.py true LDA_10 0.05 8
python webis_dbscan_script.py true LDA_10 0.05 10
python webis_dbscan_script.py true LDA_10 0.05 15
python webis_dbscan_script.py true LDA_10 0.1 2
python webis_dbscan_script.py true LDA_10 0.1 3
python webis_dbscan_script.py true LDA_10 0.1 5
python webis_dbscan_script.py true LDA_10 0.1 8
python webis_dbscan_script.py true LDA_10 0.1 10
python webis_dbscan_script.py true LDA_10 0.1 15
python webis_dbscan_script.py false LDA_10 0.2 2
python webis_dbscan_script.py false LDA_10 0.2 3
python webis_dbscan_script.py false LDA_10 0.2 5
python webis_dbscan_script.py false LDA_10 0.2 8
python webis_dbscan_script.py false LDA_10 0.2 10
python webis_dbscan_script.py false LDA_10 0.2 15
python webis_dbscan_script.py false LDA_10 0.3 2
python webis_dbscan_script.py false LDA_10 0.3 3
python webis_dbscan_script.py false LDA_10 0.3 5
python webis_dbscan_script.py false LDA_10 0.3 8
python webis_dbscan_script.py false LDA_10 0.3 10
python webis_dbscan_script.py false LDA_10 0.3 15
python webis_dbscan_script.py true LDA_25 0.05 2
python webis_dbscan_script.py true LDA_25 0.05 3
python webis_dbscan_script.py true LDA_25 0.05 5
python webis_dbscan_script.py true LDA_25 0.05 8
python webis_dbscan_script.py true LDA_25 0.05 10
python webis_dbscan_script.py true LDA_25 0.05 15
python webis_dbscan_script.py true LDA_25 0.1 2
python webis_dbscan_script.py true LDA_25 0.1 3
python webis_dbscan_script.py true LDA_25 0.1 5
python webis_dbscan_script.py true LDA_25 0.1 8
python webis_dbscan_script.py true LDA_25 0.1 10
python webis_dbscan_script.py true LDA_25 0.1 15
python webis_dbscan_script.py false LDA_25 0.2 2
python webis_dbscan_script.py false LDA_25 0.2 3
python webis_dbscan_script.py false LDA_25 0.2 5
python webis_dbscan_script.py false LDA_25 0.2 8
python webis_dbscan_script.py false LDA_25 0.2 10
python webis_dbscan_script.py false LDA_25 0.2 15
python webis_dbscan_script.py false LDA_25 0.3 2
python webis_dbscan_script.py false LDA_25 0.3 3
python webis_dbscan_script.py false LDA_25 0.3 5
python webis_dbscan_script.py false LDA_25 0.3 8
python webis_dbscan_script.py false LDA_25 0.3 10
python webis_dbscan_script.py false LDA_25 0.3 15
python webis_dbscan_script.py true LDA_50 0.05 2
python webis_dbscan_script.py true LDA_50 0.05 3
python webis_dbscan_script.py true LDA_50 0.05 5
python webis_dbscan_script.py true LDA_50 0.05 8
python webis_dbscan_script.py true LDA_50 0.05 10
python webis_dbscan_script.py true LDA_50 0.05 15
python webis_dbscan_script.py true LDA_50 0.1 2
python webis_dbscan_script.py true LDA_50 0.1 3
python webis_dbscan_script.py true LDA_50 0.1 5
python webis_dbscan_script.py true LDA_50 0.1 8
python webis_dbscan_script.py true LDA_50 0.1 10
python webis_dbscan_script.py true LDA_50 0.1 15
python webis_dbscan_script.py false LDA_50 0.2 2
python webis_dbscan_script.py false LDA_50 0.2 3
python webis_dbscan_script.py false LDA_50 0.2 5
python webis_dbscan_script.py false LDA_50 0.2 8
python webis_dbscan_script.py false LDA_50 0.2 10
python webis_dbscan_script.py false LDA_50 0.2 15
python webis_dbscan_script.py false LDA_50 0.3 2
python webis_dbscan_script.py false LDA_50 0.3 3
python webis_dbscan_script.py false LDA_50 0.3 5
python webis_dbscan_script.py false LDA_50 0.3 8
python webis_dbscan_script.py false LDA_50 0.3 10
python webis_dbscan_script.py false LDA_50 0.3 15
python webis_dbscan_script.py true Word2Vec 0.05 2
python webis_dbscan_script.py true Word2Vec 0.05 3
python webis_dbscan_script.py true Word2Vec 0.05 5
python webis_dbscan_script.py true Word2Vec 0.05 8
python webis_dbscan_script.py true Word2Vec 0.05 10
python webis_dbscan_script.py true Word2Vec 0.05 15
python webis_dbscan_script.py true Word2Vec 0.1 2
python webis_dbscan_script.py true Word2Vec 0.1 3
python webis_dbscan_script.py true Word2Vec 0.1 5
python webis_dbscan_script.py true Word2Vec 0.1 8
python webis_dbscan_script.py true Word2Vec 0.1 10
python webis_dbscan_script.py true Word2Vec 0.1 15
python webis_dbscan_script.py false Word2Vec 0.2 2
python webis_dbscan_script.py false Word2Vec 0.2 3
python webis_dbscan_script.py false Word2Vec 0.2 5
python webis_dbscan_script.py false Word2Vec 0.2 8
python webis_dbscan_script.py false Word2Vec 0.2 10
python webis_dbscan_script.py false Word2Vec 0.2 15
python webis_dbscan_script.py false Word2Vec 0.3 2
python webis_dbscan_script.py false Word2Vec 0.3 3
python webis_dbscan_script.py false Word2Vec 0.3 5
python webis_dbscan_script.py false Word2Vec 0.3 8
python webis_dbscan_script.py false Word2Vec 0.3 10
python webis_dbscan_script.py false Word2Vec 0.3 15
python webis_dbscan_script.py true Glove 0.05 2
python webis_dbscan_script.py true Glove 0.05 3
python webis_dbscan_script.py true Glove 0.05 5
python webis_dbscan_script.py true Glove 0.05 8
python webis_dbscan_script.py true Glove 0.05 10
python webis_dbscan_script.py true Glove 0.05 15
python webis_dbscan_script.py true Glove 0.1 2
python webis_dbscan_script.py true Glove 0.1 3
python webis_dbscan_script.py true Glove 0.1 5
python webis_dbscan_script.py true Glove 0.1 8
python webis_dbscan_script.py true Glove 0.1 10
python webis_dbscan_script.py true Glove 0.1 15
python webis_dbscan_script.py false Glove 0.2 2
python webis_dbscan_script.py false Glove 0.2 3
python webis_dbscan_script.py false Glove 0.2 5
python webis_dbscan_script.py false Glove 0.2 8
python webis_dbscan_script.py false Glove 0.2 10
python webis_dbscan_script.py false Glove 0.2 15
python webis_dbscan_script.py false Glove 0.3 2
python webis_dbscan_script.py false Glove 0.3 3
python webis_dbscan_script.py false Glove 0.3 5
python webis_dbscan_script.py false Glove 0.3 8
python webis_dbscan_script.py false Glove 0.3 10
python webis_dbscan_script.py false Glove 0.3 15
python webis_dbscan_script.py true Doc2Vec 0.05 2
python webis_dbscan_script.py true Doc2Vec 0.05 3
python webis_dbscan_script.py true Doc2Vec 0.05 5
python webis_dbscan_script.py true Doc2Vec 0.05 8
python webis_dbscan_script.py true Doc2Vec 0.05 10
python webis_dbscan_script.py true Doc2Vec 0.05 15
python webis_dbscan_script.py true Doc2Vec 0.1 2
python webis_dbscan_script.py true Doc2Vec 0.1 3
python webis_dbscan_script.py true Doc2Vec 0.1 5
python webis_dbscan_script.py true Doc2Vec 0.1 8
python webis_dbscan_script.py true Doc2Vec 0.1 10
python webis_dbscan_script.py true Doc2Vec 0.1 15
python webis_dbscan_script.py false Doc2Vec 0.2 2
python webis_dbscan_script.py false Doc2Vec 0.2 3
python webis_dbscan_script.py false Doc2Vec 0.2 5
python webis_dbscan_script.py false Doc2Vec 0.2 8
python webis_dbscan_script.py false Doc2Vec 0.2 10
python webis_dbscan_script.py false Doc2Vec 0.2 15
python webis_dbscan_script.py false Doc2Vec 0.3 2
python webis_dbscan_script.py false Doc2Vec 0.3 3
python webis_dbscan_script.py false Doc2Vec 0.3 5
python webis_dbscan_script.py false Doc2Vec 0.3 8
python webis_dbscan_script.py false Doc2Vec 0.3 10
python webis_dbscan_script.py false Doc2Vec 0.3 15
